 version: 2
 jobs:
   build:
     working_directory: ~/build # directory where steps will run
     docker:
       - image: number9/libstapsdt
     steps:
       - checkout
       - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
       - run:
          name: install-npm-wee
          command: npm install
       - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
       - run: # run tests
          name: test
          command: npm test